quarkus:
    datasource:
        db-kind: h2
        jdbc:
            url:  jdbc:h2:mem:todo
    hibernate-orm:
        dialect: org.hibernate.dialect.H2Dialect
        database:
            generation: drop-and-create
